### ISSUE TITLE
Look for ESCs

### ISSUE THREAD

**Issue by jspspike** [ut-ras/robomaster#17]
So we're planning on use the ones that come with [m3508](https://www.robomaster.com/en-US/products/components/general/M3508) but maybe considering using hobby brushless escs like [these](https://www.amazon.com/iFlight-BLHeli_S-Electronic-Controller-Quadcopter/dp/B07WDRW249/ref=pd_lpo_21_t_0/135-1041589-2207619?_encoding=UTF8&pd_rd_i=B07WDRW249&pd_rd_r=f841c06e-941f-493d-9b15-18947e37749c&pd_rd_w=fPf4S&pd_rd_wg=zSRAZ&pf_rd_p=16b28406-aa34-451d-8a2e-b3930ada000c&pf_rd_r=XG7JZ012Q9MNFA3TNSFZ&psc=1&refRID=XG7JZ012Q9MNFA3TNSFZ). Look for other hobby escs that are 6s and fit within our current draw.

**Comment by jared01m** [comment]
There are a lot of good 4 in 1 ESCs out there, but the issue is with the 7-pin cable that attaches to the motor. If we go with an ESC that's not the one provided by Robomaster, we won't get position feedback, temperature detection, or information storage. Apart from that, we need an ESC that can take 6S and if we want 32 bit like the Robomaster ones, then we need BLHeli-32 ESCs.
