### ISSUE TITLE
Add Automatic Agitator Unjamming

### ISSUE THREAD

**Issue by eddieliao** [ut-ras/robomaster#69]
This will probably be easy once we add the code to control firing more accurately (e.g. burst fire #68).

**Comment by calebchalmers** [comment]
Easiest way will be to use a taproot timer and detect if the motor has been at a low velocity for longer than a certain period of time. We will have to play with the velocity and time thresholds, but this should be simple to implement.

We may have to worry about starting conditions, since agitators will take some time to get up to speed; however, this is very fast, so it shouldn't be a huge issue.
